version: '2'
services:
  mongo:
    image: mongo
  nginx:
    image: nginx
    volumes:
      - ./ReduxOmdb/dist:/var/www/
      - ./default:/etc/nginx/conf.d/default.conf
    environment:
     - NGINX_PORT=80
    links:
      - "web:web"
    ports:
      - "80:80"
    

  web:
    build: .
    command:  npm start
    volumes:
      - ./OmdbBack/bin:/app/bin
      - ./OmdbBack/config:/app/config
      - ./OmdbBack/middleware:/app/middleware
      - ./OmdbBack/models:/app/models
      - ./OmdbBack/routes:/app/routes
      - ./OmdbBack/views:/app/views
      - ./OmdbBack/public:/app/public
    links:
      - "mongo:mongo"
    ports:
      - "3000:3000"
